# Generated by Django 5.0.2 on 2024-03-05 14:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('medicine', '0004_alter_product_category'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
